% Contains all the Global variables for TVWSS Adaptive DSSS code
% 
% Author: Sanjib Sur
% Institute: University of Wisconsin - Madison
% Version: 0.0.1
% Last modified: 06/22/2014
% 
% Comments: This file contains all the global variables used across
% different files and functions of the TVWS Adaptive DSSS PHY layer 
% implementation which uses WURC + WARP boards.
% 
% 

global SIMSNR DEBUG_ON useFakeChannel VERBOSE1 VERBOSE2 USESIM osamp ...
    Txparams Rxparams Timeparams Preamble Payload Packet padding_size ...
    Padding TRACE_DRIVEN TRACE_COLLECT TRACE_DRIVEN_REGRESSION ...
    channel_trace_file channel_trace_file_handle channel_trace_data ...
    channel_trace_idx addFreqOffset freq_offset_val ...
    WARPLab_TxDelay WARPLab_TxLength WARPLab_CarrierChannel ...
    WARPLab_TxGain_RF WARPLab_TxGain_BB WARPLab_RxGain_BB ...
    WARPLab_RxGain_RF WARPLab_Frequency WARPLab_node_tx ...
    WARPLab_node_rx WARPLab_RF_vector WARPLab_eth_trig Fs ...
    WURC WURC_FLAG_IS_BOARD_GREEN WURC_gainTX_wsd_n WURC_gainRX_wsd_db ...
    WURC_gainRX_warp_rf WURC_gainRX_warp_bb WURC_agc_WARP_target ...
    WURC_agc_WSD_target WURC_channel_wsd WURC_NUMNODES WURC_node_tx ...
    WURC_node_rx WURC_RF_TX WURC_RF_RX WURC_TxDelay WURC_TxLength ...
    WURC_eth_trig ...
    inbits outbits hmodem hdemodem symb2BitNum ...
    TxConstellation RxConstellation fake_channel trace_channel ...
    awgn_channel globalTimestamp DSSSCode ...
    PKT_SYNC_VECTOR PKT_SFD_VECTOR PKT_RSFD_VECTOR PKT_SYNC_COUNT ...
    bits_per_chunk SYNC_ERROR_THRESHOLD SKIP_ONES CORR_THRESHOLD SPB ...
    LOG_TABLE RSSI_AVE_COUNT RSSI_MAX RSSI RAW_ENERGY PKT_SNR;